language: java
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
install: mvn install -DskipTests=true -Dgpg.skip=true
before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y r-recommended r-cran-rserve
